
-- Create the employees table
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    age INTEGER,
    department TEXT,
    position TEXT,
    salary REAL,
    year_joined INTEGER,
    region TEXT
);

-- Insert random records into the table
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_0', 51, 'Marketing', 'Brand Manager', 91730, 2011, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_1', 58, 'Marketing', 'SEO Specialist', 59554, 2018, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_2', 48, 'Marketing', 'Brand Manager', 72996, 2001, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_3', 47, 'Finance', 'Accountant', 89272, 2020, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_4', 57, 'Engineering', 'Software Engineer', 99264, 2007, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_5', 33, 'Engineering', 'Data Engineer', 100225, 2003, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_6', 24, 'Engineering', 'Software Engineer', 87455, 2006, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_7', 28, 'Finance', 'Finance Manager', 115214, 2000, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_8', 53, 'Marketing', 'Marketing Coordinator', 50437, 2018, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_9', 26, 'Engineering', 'Software Engineer', 108450, 2011, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_10', 31, 'Marketing', 'Marketing Coordinator', 79637, 2012, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_11', 58, 'HR', 'Talent Acquisition', 82225, 2024, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_12', 37, 'Operations', 'Logistics Manager', 66674, 2016, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_13', 52, 'Marketing', 'SEO Specialist', 56570, 2009, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_14', 42, 'Marketing', 'SEO Specialist', 55742, 2023, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_15', 46, 'HR', 'HR Manager', 98786, 2017, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_16', 49, 'Operations', 'Supply Chain Analyst', 75460, 2016, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_17', 56, 'Engineering', 'ML Engineer', 144387, 2011, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_18', 30, 'HR', 'HR Manager', 81350, 2007, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_19', 37, 'Sales', 'Account Executive', 55272, 2001, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_20', 59, 'Operations', 'Supply Chain Analyst', 93744, 2023, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_21', 49, 'HR', 'HR Manager', 83483, 2023, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_22', 24, 'Sales', 'Sales Associate', 45906, 2020, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_23', 45, 'Engineering', 'DevOps Engineer', 98613, 2001, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_24', 58, 'Operations', 'Supply Chain Analyst', 85617, 2018, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_25', 31, 'Operations', 'Supply Chain Analyst', 68386, 2010, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_26', 27, 'HR', 'HR Coordinator', 49471, 2004, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_27', 37, 'Engineering', 'Data Engineer', 91643, 2013, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_28', 38, 'Sales', 'Sales Associate', 61848, 2005, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_29', 37, 'Engineering', 'Data Engineer', 71662, 2007, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_30', 30, 'Finance', 'Finance Manager', 75811, 2015, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_31', 42, 'Operations', 'Operations Coordinator', 61450, 2010, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_32', 53, 'Operations', 'Logistics Manager', 70777, 2021, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_33', 43, 'HR', 'Talent Acquisition', 60761, 2020, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_34', 35, 'HR', 'HR Manager', 102131, 2005, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_35', 31, 'Operations', 'Supply Chain Analyst', 88758, 2011, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_36', 49, 'Engineering', 'Software Engineer', 99332, 2007, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_37', 29, 'Finance', 'Accountant', 90011, 2021, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_38', 37, 'Marketing', 'Marketing Coordinator', 45404, 2021, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_39', 23, 'Finance', 'Finance Manager', 87323, 2002, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_40', 31, 'Sales', 'Sales Associate', 73003, 2021, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_41', 54, 'Marketing', 'Brand Manager', 62904, 2004, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_42', 43, 'HR', 'HR Coordinator', 63814, 2020, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_43', 39, 'Operations', 'Logistics Manager', 87091, 2024, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_44', 46, 'Engineering', 'Software Engineer', 99825, 2002, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_45', 50, 'Marketing', 'Marketing Coordinator', 81278, 2022, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_46', 36, 'Finance', 'Financial Analyst', 102279, 2007, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_47', 22, 'Marketing', 'SEO Specialist', 82994, 2012, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_48', 23, 'Operations', 'Logistics Manager', 72607, 2019, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_49', 47, 'Finance', 'Finance Manager', 78147, 2013, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_50', 24, 'Sales', 'Account Executive', 77652, 2004, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_51', 49, 'Marketing', 'Brand Manager', 60113, 2008, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_52', 53, 'Marketing', 'Marketing Coordinator', 73936, 2017, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_53', 54, 'Sales', 'Account Executive', 59944, 2006, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_54', 42, 'Engineering', 'Software Engineer', 88772, 2001, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_55', 47, 'HR', 'HR Manager', 96973, 2002, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_56', 48, 'Engineering', 'DevOps Engineer', 78873, 2013, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_57', 58, 'Marketing', 'SEO Specialist', 50281, 2019, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_58', 37, 'Engineering', 'DevOps Engineer', 108728, 2000, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_59', 60, 'HR', 'HR Coordinator', 53545, 2022, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_60', 59, 'Marketing', 'Marketing Coordinator', 71870, 2013, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_61', 36, 'Operations', 'Logistics Manager', 83660, 2017, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_62', 33, 'Finance', 'Accountant', 79920, 2014, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_63', 34, 'Sales', 'Sales Manager', 92590, 2015, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_64', 27, 'Operations', 'Supply Chain Analyst', 80176, 2022, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_65', 42, 'Marketing', 'Brand Manager', 67860, 2009, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_66', 55, 'Finance', 'Financial Analyst', 82405, 2015, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_67', 58, 'Operations', 'Supply Chain Analyst', 65093, 2024, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_68', 36, 'Sales', 'Account Executive', 65129, 2008, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_69', 58, 'Sales', 'Sales Associate', 51039, 2000, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_70', 35, 'Engineering', 'DevOps Engineer', 130779, 2016, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_71', 25, 'Operations', 'Operations Coordinator', 55331, 2018, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_72', 31, 'Operations', 'Supply Chain Analyst', 77892, 2018, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_73', 57, 'Sales', 'Account Executive', 76787, 2021, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_74', 34, 'Marketing', 'Brand Manager', 77164, 2023, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_75', 49, 'Finance', 'Accountant', 75518, 2017, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_76', 52, 'Marketing', 'Brand Manager', 81004, 2009, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_77', 59, 'Finance', 'Accountant', 59308, 2015, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_78', 28, 'HR', 'HR Manager', 77539, 2015, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_79', 40, 'HR', 'HR Coordinator', 59444, 2011, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_80', 44, 'Marketing', 'Brand Manager', 74916, 2001, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_81', 48, 'Finance', 'Financial Analyst', 98743, 2020, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_82', 29, 'Marketing', 'SEO Specialist', 52154, 2024, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_83', 42, 'Operations', 'Logistics Manager', 83034, 2011, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_84', 35, 'Finance', 'Financial Analyst', 67784, 2000, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_85', 23, 'Engineering', 'Software Engineer', 65078, 2021, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_86', 52, 'Operations', 'Operations Coordinator', 71096, 2024, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_87', 53, 'Operations', 'Logistics Manager', 60853, 2024, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_88', 47, 'Marketing', 'SEO Specialist', 52591, 2008, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_89', 33, 'Sales', 'Account Executive', 58190, 2015, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_90', 41, 'HR', 'Talent Acquisition', 88449, 2006, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_91', 59, 'Operations', 'Operations Coordinator', 64504, 2002, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_92', 41, 'Operations', 'Logistics Manager', 67693, 2007, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_93', 28, 'Operations', 'Logistics Manager', 74409, 2008, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_94', 31, 'Marketing', 'Brand Manager', 61816, 2014, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_95', 37, 'Sales', 'Sales Associate', 62138, 2014, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_96', 34, 'Sales', 'Account Executive', 79568, 2013, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_97', 59, 'Engineering', 'DevOps Engineer', 100567, 2005, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_98', 44, 'Sales', 'Sales Manager', 95137, 2011, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_99', 42, 'Engineering', 'Software Engineer', 67527, 2017, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_100', 56, 'HR', 'HR Coordinator', 62061, 2019, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_101', 26, 'Engineering', 'Data Engineer', 110165, 2002, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_102', 23, 'HR', 'HR Coordinator', 62343, 2018, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_103', 22, 'Sales', 'Sales Associate', 41184, 2003, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_104', 55, 'Marketing', 'Brand Manager', 72579, 2022, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_105', 25, 'Operations', 'Operations Coordinator', 77343, 2002, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_106', 48, 'Marketing', 'Brand Manager', 97405, 2024, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_107', 38, 'Sales', 'Sales Associate', 61460, 2001, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_108', 50, 'Engineering', 'Software Engineer', 106580, 2004, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_109', 40, 'Sales', 'Account Executive', 61827, 2009, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_110', 23, 'Marketing', 'Marketing Coordinator', 65057, 2022, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_111', 54, 'Operations', 'Supply Chain Analyst', 82449, 2004, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_112', 31, 'Engineering', 'Software Engineer', 87835, 2023, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_113', 56, 'HR', 'Talent Acquisition', 68086, 2016, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_114', 46, 'Operations', 'Operations Coordinator', 70141, 2003, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_115', 23, 'Operations', 'Supply Chain Analyst', 56964, 2001, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_116', 27, 'HR', 'HR Manager', 105310, 2019, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_117', 44, 'Marketing', 'Marketing Coordinator', 75289, 2000, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_118', 36, 'Engineering', 'DevOps Engineer', 82196, 2013, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_119', 49, 'Marketing', 'Brand Manager', 76136, 2017, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_120', 29, 'Marketing', 'Brand Manager', 97350, 2023, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_121', 41, 'Operations', 'Logistics Manager', 74140, 2015, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_122', 45, 'Engineering', 'DevOps Engineer', 107074, 2011, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_123', 51, 'Marketing', 'SEO Specialist', 92915, 2019, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_124', 23, 'Engineering', 'DevOps Engineer', 119948, 2022, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_125', 46, 'HR', 'HR Manager', 81281, 2015, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_126', 34, 'Operations', 'Logistics Manager', 91525, 2007, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_127', 23, 'HR', 'HR Coordinator', 59541, 2012, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_128', 27, 'HR', 'HR Manager', 65905, 2015, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_129', 29, 'Engineering', 'Software Engineer', 77618, 2004, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_130', 54, 'Finance', 'Financial Analyst', 84760, 2023, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_131', 31, 'Operations', 'Logistics Manager', 66724, 2024, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_132', 56, 'Marketing', 'Marketing Coordinator', 70490, 2004, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_133', 34, 'Sales', 'Sales Associate', 76246, 2021, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_134', 54, 'Marketing', 'Brand Manager', 99410, 2015, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_135', 27, 'HR', 'HR Manager', 83561, 2018, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_136', 34, 'HR', 'HR Coordinator', 72200, 2007, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_137', 35, 'Finance', 'Financial Analyst', 75395, 2014, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_138', 45, 'Operations', 'Supply Chain Analyst', 72954, 2013, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_139', 56, 'Finance', 'Finance Manager', 119082, 2018, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_140', 45, 'Operations', 'Operations Coordinator', 51283, 2018, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_141', 50, 'Sales', 'Sales Manager', 104297, 2014, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_142', 52, 'Operations', 'Supply Chain Analyst', 60718, 2002, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_143', 22, 'Finance', 'Financial Analyst', 103981, 2000, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_144', 40, 'HR', 'HR Coordinator', 70651, 2004, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_145', 25, 'Marketing', 'Marketing Coordinator', 67164, 2018, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_146', 36, 'HR', 'HR Manager', 85061, 2007, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_147', 36, 'Operations', 'Operations Coordinator', 65215, 2024, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_148', 38, 'Engineering', 'DevOps Engineer', 82924, 2009, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_149', 24, 'Marketing', 'SEO Specialist', 56179, 2017, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_150', 39, 'Finance', 'Accountant', 67291, 2008, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_151', 38, 'Engineering', 'ML Engineer', 131031, 2015, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_152', 34, 'Sales', 'Sales Manager', 69044, 2023, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_153', 56, 'Sales', 'Account Executive', 67901, 2011, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_154', 53, 'HR', 'HR Manager', 107917, 2021, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_155', 59, 'Sales', 'Sales Associate', 75556, 2016, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_156', 33, 'Operations', 'Logistics Manager', 109378, 2006, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_157', 59, 'HR', 'HR Manager', 91954, 2002, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_158', 41, 'Finance', 'Accountant', 63182, 2010, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_159', 59, 'Operations', 'Operations Coordinator', 78883, 2018, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_160', 48, 'Engineering', 'DevOps Engineer', 120581, 2007, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_161', 48, 'HR', 'HR Manager', 86097, 2007, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_162', 56, 'Sales', 'Account Executive', 87863, 2015, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_163', 22, 'Engineering', 'Data Engineer', 86613, 2017, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_164', 43, 'HR', 'HR Coordinator', 69233, 2019, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_165', 52, 'Sales', 'Account Executive', 52364, 2004, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_166', 31, 'Engineering', 'Data Engineer', 78126, 2016, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_167', 43, 'Operations', 'Supply Chain Analyst', 59663, 2005, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_168', 22, 'Marketing', 'Brand Manager', 93482, 2000, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_169', 60, 'Finance', 'Financial Analyst', 76815, 2022, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_170', 31, 'Operations', 'Operations Coordinator', 57239, 2000, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_171', 47, 'Marketing', 'SEO Specialist', 86832, 2010, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_172', 52, 'Engineering', 'DevOps Engineer', 125456, 2012, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_173', 22, 'HR', 'HR Manager', 81342, 2017, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_174', 27, 'Finance', 'Finance Manager', 105996, 2020, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_175', 44, 'Sales', 'Sales Associate', 41282, 2008, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_176', 38, 'Engineering', 'ML Engineer', 149007, 2006, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_177', 22, 'Operations', 'Operations Coordinator', 67481, 2014, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_178', 44, 'Marketing', 'Brand Manager', 94403, 2005, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_179', 44, 'Marketing', 'Marketing Coordinator', 60085, 2005, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_180', 47, 'Marketing', 'Brand Manager', 81741, 2008, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_181', 51, 'Operations', 'Operations Coordinator', 56203, 2010, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_182', 29, 'Finance', 'Finance Manager', 83530, 2022, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_183', 53, 'Engineering', 'DevOps Engineer', 136262, 2013, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_184', 34, 'Operations', 'Supply Chain Analyst', 74637, 2004, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_185', 50, 'Finance', 'Financial Analyst', 81146, 2002, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_186', 35, 'Operations', 'Logistics Manager', 107367, 2000, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_187', 56, 'Finance', 'Finance Manager', 107986, 2023, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_188', 24, 'Finance', 'Finance Manager', 120109, 2022, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_189', 43, 'Sales', 'Sales Associate', 78966, 2007, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_190', 30, 'Sales', 'Sales Manager', 73971, 2013, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_191', 59, 'Finance', 'Accountant', 64709, 2017, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_192', 30, 'Operations', 'Logistics Manager', 69391, 2020, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_193', 44, 'Engineering', 'ML Engineer', 95271, 2019, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_194', 57, 'Sales', 'Sales Manager', 102898, 2000, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_195', 36, 'HR', 'HR Manager', 86791, 2020, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_196', 34, 'Engineering', 'DevOps Engineer', 116184, 2024, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_197', 59, 'Operations', 'Supply Chain Analyst', 67570, 2020, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_198', 60, 'Sales', 'Account Executive', 52104, 2002, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_199', 25, 'HR', 'HR Coordinator', 57420, 2004, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_200', 26, 'Marketing', 'Marketing Coordinator', 76575, 2014, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_201', 39, 'Operations', 'Operations Coordinator', 83572, 2002, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_202', 31, 'Finance', 'Financial Analyst', 95203, 2000, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_203', 36, 'Operations', 'Logistics Manager', 98866, 2003, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_204', 44, 'HR', 'Talent Acquisition', 76350, 2008, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_205', 50, 'Operations', 'Operations Coordinator', 65177, 2002, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_206', 39, 'Sales', 'Account Executive', 84201, 2001, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_207', 25, 'Sales', 'Sales Manager', 93232, 2012, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_208', 50, 'Operations', 'Operations Coordinator', 83146, 2016, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_209', 56, 'Marketing', 'Brand Manager', 79882, 2003, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_210', 34, 'Sales', 'Sales Manager', 65463, 2019, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_211', 36, 'Operations', 'Logistics Manager', 60521, 2010, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_212', 49, 'Operations', 'Operations Coordinator', 69424, 2023, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_213', 46, 'HR', 'HR Manager', 77976, 2021, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_214', 59, 'Sales', 'Account Executive', 74938, 2014, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_215', 55, 'Sales', 'Sales Associate', 40733, 2019, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_216', 22, 'Finance', 'Accountant', 72274, 2023, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_217', 45, 'Engineering', 'Software Engineer', 88770, 2016, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_218', 25, 'Sales', 'Sales Manager', 60940, 2011, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_219', 25, 'Marketing', 'Brand Manager', 78067, 2009, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_220', 54, 'Sales', 'Sales Associate', 66270, 2010, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_221', 34, 'HR', 'HR Manager', 69590, 2012, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_222', 23, 'HR', 'HR Manager', 83997, 2011, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_223', 26, 'Sales', 'Sales Associate', 65868, 2008, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_224', 28, 'Finance', 'Accountant', 75209, 2020, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_225', 58, 'Engineering', 'Software Engineer', 68361, 2019, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_226', 25, 'Engineering', 'DevOps Engineer', 95593, 2003, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_227', 53, 'Engineering', 'ML Engineer', 142588, 2024, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_228', 57, 'Operations', 'Operations Coordinator', 79624, 2008, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_229', 26, 'Marketing', 'SEO Specialist', 80181, 2010, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_230', 34, 'Operations', 'Operations Coordinator', 51129, 2023, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_231', 45, 'Operations', 'Operations Coordinator', 68059, 2001, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_232', 55, 'HR', 'HR Coordinator', 52692, 2009, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_233', 53, 'Finance', 'Finance Manager', 108541, 2010, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_234', 49, 'HR', 'Talent Acquisition', 79372, 2000, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_235', 28, 'Sales', 'Sales Associate', 45582, 2016, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_236', 44, 'Finance', 'Financial Analyst', 76932, 2020, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_237', 31, 'Sales', 'Account Executive', 76577, 2007, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_238', 37, 'Marketing', 'SEO Specialist', 80319, 2012, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_239', 46, 'HR', 'HR Coordinator', 53999, 2004, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_240', 31, 'Finance', 'Finance Manager', 86336, 2004, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_241', 49, 'HR', 'HR Manager', 90682, 2013, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_242', 32, 'HR', 'Talent Acquisition', 72436, 2005, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_243', 31, 'Marketing', 'Brand Manager', 91964, 2011, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_244', 43, 'Marketing', 'Brand Manager', 70192, 2006, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_245', 60, 'Marketing', 'Marketing Coordinator', 57364, 2012, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_246', 45, 'Sales', 'Sales Associate', 49510, 2007, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_247', 42, 'Finance', 'Accountant', 60289, 2014, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_248', 33, 'Marketing', 'SEO Specialist', 51635, 2014, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_249', 29, 'Finance', 'Finance Manager', 93124, 2014, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_250', 55, 'Engineering', 'Data Engineer', 115833, 2022, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_251', 50, 'Engineering', 'Data Engineer', 87752, 2022, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_252', 51, 'Sales', 'Sales Manager', 62562, 2018, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_253', 43, 'HR', 'Talent Acquisition', 85491, 2001, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_254', 53, 'HR', 'HR Coordinator', 48070, 2017, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_255', 44, 'HR', 'HR Manager', 108296, 2002, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_256', 29, 'Engineering', 'Software Engineer', 70370, 2022, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_257', 31, 'Operations', 'Logistics Manager', 74985, 2007, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_258', 33, 'Sales', 'Sales Manager', 72332, 2005, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_259', 58, 'Operations', 'Logistics Manager', 106308, 2019, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_260', 60, 'Marketing', 'Brand Manager', 104544, 2014, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_261', 51, 'Engineering', 'ML Engineer', 97283, 2004, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_262', 43, 'Engineering', 'Data Engineer', 102875, 2013, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_263', 57, 'Operations', 'Operations Coordinator', 78904, 2000, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_264', 59, 'Operations', 'Supply Chain Analyst', 82745, 2015, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_265', 41, 'Operations', 'Supply Chain Analyst', 93645, 2024, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_266', 43, 'HR', 'HR Manager', 104457, 2019, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_267', 59, 'HR', 'HR Manager', 101566, 2001, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_268', 60, 'HR', 'Talent Acquisition', 85149, 2016, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_269', 42, 'Sales', 'Sales Associate', 46320, 2013, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_270', 44, 'HR', 'HR Coordinator', 73890, 2021, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_271', 43, 'Sales', 'Sales Associate', 60514, 2010, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_272', 46, 'Operations', 'Logistics Manager', 104511, 2021, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_273', 28, 'Engineering', 'ML Engineer', 109719, 2023, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_274', 23, 'Marketing', 'Brand Manager', 60214, 2001, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_275', 33, 'Engineering', 'Data Engineer', 106518, 2020, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_276', 26, 'Marketing', 'Marketing Coordinator', 77708, 2000, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_277', 41, 'HR', 'HR Manager', 100585, 2009, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_278', 48, 'Engineering', 'Software Engineer', 68924, 2016, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_279', 55, 'Marketing', 'SEO Specialist', 92309, 2000, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_280', 43, 'Operations', 'Supply Chain Analyst', 91055, 2012, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_281', 53, 'HR', 'HR Manager', 70320, 2017, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_282', 42, 'Operations', 'Supply Chain Analyst', 63450, 2004, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_283', 23, 'Operations', 'Supply Chain Analyst', 69544, 2022, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_284', 42, 'Marketing', 'Marketing Coordinator', 71611, 2024, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_285', 29, 'HR', 'Talent Acquisition', 88273, 2019, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_286', 55, 'HR', 'HR Manager', 78406, 2008, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_287', 58, 'Sales', 'Sales Associate', 47107, 2023, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_288', 48, 'HR', 'HR Manager', 108043, 2003, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_289', 38, 'HR', 'Talent Acquisition', 51325, 2001, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_290', 53, 'Operations', 'Logistics Manager', 100385, 2010, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_291', 57, 'Operations', 'Logistics Manager', 62434, 2013, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_292', 47, 'Sales', 'Sales Manager', 78928, 2020, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_293', 45, 'Operations', 'Operations Coordinator', 64094, 2018, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_294', 51, 'Operations', 'Operations Coordinator', 68942, 2008, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_295', 36, 'Finance', 'Finance Manager', 86250, 2010, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_296', 39, 'Sales', 'Sales Associate', 49280, 2007, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_297', 32, 'Operations', 'Supply Chain Analyst', 92283, 2006, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_298', 36, 'Sales', 'Sales Manager', 87832, 2012, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_299', 54, 'Engineering', 'Data Engineer', 99047, 2021, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_300', 47, 'Engineering', 'Software Engineer', 73845, 2002, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_301', 57, 'Operations', 'Supply Chain Analyst', 87859, 2014, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_302', 48, 'Sales', 'Sales Associate', 50626, 2021, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_303', 43, 'Marketing', 'SEO Specialist', 59180, 2006, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_304', 53, 'HR', 'Talent Acquisition', 54534, 2006, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_305', 23, 'Operations', 'Supply Chain Analyst', 66730, 2021, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_306', 26, 'Finance', 'Financial Analyst', 80254, 2011, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_307', 36, 'Operations', 'Operations Coordinator', 58552, 2004, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_308', 41, 'HR', 'Talent Acquisition', 64866, 2001, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_309', 37, 'Marketing', 'Brand Manager', 104026, 2001, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_310', 45, 'Operations', 'Supply Chain Analyst', 81860, 2014, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_311', 28, 'Operations', 'Logistics Manager', 80716, 2019, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_312', 46, 'HR', 'Talent Acquisition', 82936, 2006, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_313', 26, 'Marketing', 'SEO Specialist', 63022, 2000, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_314', 47, 'Marketing', 'Brand Manager', 92415, 2004, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_315', 37, 'Engineering', 'Data Engineer', 121690, 2014, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_316', 48, 'Finance', 'Accountant', 68944, 2016, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_317', 35, 'Marketing', 'SEO Specialist', 55879, 2015, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_318', 35, 'Finance', 'Finance Manager', 83802, 2001, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_319', 57, 'Marketing', 'Brand Manager', 98642, 2021, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_320', 28, 'Marketing', 'Marketing Coordinator', 76274, 2006, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_321', 30, 'Operations', 'Supply Chain Analyst', 98338, 2024, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_322', 53, 'Finance', 'Accountant', 86608, 2001, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_323', 46, 'Operations', 'Operations Coordinator', 68869, 2009, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_324', 52, 'HR', 'HR Coordinator', 51269, 2002, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_325', 29, 'Finance', 'Finance Manager', 129955, 2020, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_326', 48, 'Engineering', 'Software Engineer', 83060, 2021, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_327', 33, 'Finance', 'Financial Analyst', 90976, 2021, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_328', 42, 'Engineering', 'Data Engineer', 85634, 2009, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_329', 36, 'HR', 'HR Coordinator', 70946, 2002, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_330', 36, 'Engineering', 'DevOps Engineer', 86455, 2015, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_331', 39, 'Engineering', 'Data Engineer', 112490, 2013, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_332', 26, 'Operations', 'Operations Coordinator', 67584, 2002, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_333', 54, 'Engineering', 'DevOps Engineer', 135782, 2014, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_334', 23, 'Operations', 'Logistics Manager', 99831, 2012, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_335', 25, 'Finance', 'Financial Analyst', 90599, 2001, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_336', 48, 'HR', 'HR Manager', 67242, 2009, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_337', 52, 'Marketing', 'Brand Manager', 63531, 2005, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_338', 37, 'Operations', 'Operations Coordinator', 59013, 2024, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_339', 38, 'Operations', 'Supply Chain Analyst', 72571, 2015, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_340', 43, 'HR', 'Talent Acquisition', 72989, 2004, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_341', 44, 'Sales', 'Account Executive', 89872, 2021, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_342', 28, 'HR', 'HR Coordinator', 50891, 2020, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_343', 58, 'Marketing', 'Marketing Coordinator', 69883, 2021, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_344', 58, 'Sales', 'Account Executive', 68483, 2003, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_345', 29, 'Sales', 'Sales Associate', 50913, 2013, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_346', 37, 'Finance', 'Accountant', 70637, 2020, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_347', 48, 'HR', 'HR Coordinator', 67613, 2021, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_348', 57, 'Sales', 'Sales Associate', 71343, 2002, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_349', 58, 'Marketing', 'Brand Manager', 82587, 2005, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_350', 27, 'Finance', 'Financial Analyst', 97493, 2022, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_351', 56, 'Operations', 'Operations Coordinator', 64992, 2000, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_352', 25, 'Finance', 'Finance Manager', 83003, 2004, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_353', 43, 'Marketing', 'Brand Manager', 75186, 2019, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_354', 24, 'HR', 'Talent Acquisition', 57920, 2023, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_355', 58, 'Finance', 'Financial Analyst', 71682, 2007, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_356', 38, 'Finance', 'Accountant', 91793, 2018, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_357', 59, 'Engineering', 'DevOps Engineer', 98861, 2005, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_358', 48, 'Finance', 'Financial Analyst', 71387, 2017, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_359', 55, 'Operations', 'Supply Chain Analyst', 55378, 2006, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_360', 40, 'Sales', 'Sales Manager', 93470, 2016, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_361', 29, 'HR', 'HR Coordinator', 78822, 2000, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_362', 47, 'Sales', 'Account Executive', 80139, 2000, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_363', 48, 'Marketing', 'Marketing Coordinator', 65006, 2004, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_364', 41, 'Sales', 'Sales Associate', 60894, 2010, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_365', 26, 'Sales', 'Sales Manager', 90314, 2000, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_366', 47, 'HR', 'Talent Acquisition', 61814, 2019, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_367', 55, 'Operations', 'Operations Coordinator', 72473, 2005, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_368', 48, 'Marketing', 'SEO Specialist', 91962, 2008, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_369', 50, 'Engineering', 'Software Engineer', 99452, 2016, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_370', 54, 'HR', 'HR Coordinator', 63426, 2001, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_371', 49, 'Sales', 'Sales Associate', 44981, 2002, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_372', 27, 'Marketing', 'SEO Specialist', 74111, 2000, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_373', 48, 'Marketing', 'Brand Manager', 77891, 2000, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_374', 40, 'HR', 'Talent Acquisition', 70206, 2000, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_375', 55, 'Marketing', 'SEO Specialist', 84142, 2008, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_376', 50, 'Operations', 'Logistics Manager', 103203, 2017, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_377', 26, 'Marketing', 'Brand Manager', 72007, 2017, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_378', 23, 'Operations', 'Supply Chain Analyst', 72104, 2012, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_379', 54, 'Marketing', 'Marketing Coordinator', 71187, 2000, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_380', 45, 'Sales', 'Account Executive', 84447, 2002, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_381', 54, 'Sales', 'Account Executive', 81081, 2005, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_382', 30, 'Finance', 'Financial Analyst', 87637, 2014, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_383', 52, 'Operations', 'Supply Chain Analyst', 71623, 2002, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_384', 26, 'Marketing', 'SEO Specialist', 54184, 2001, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_385', 39, 'Sales', 'Sales Manager', 92623, 2011, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_386', 45, 'Engineering', 'DevOps Engineer', 120583, 2024, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_387', 59, 'Engineering', 'Data Engineer', 90514, 2010, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_388', 45, 'HR', 'Talent Acquisition', 79657, 2001, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_389', 60, 'Operations', 'Supply Chain Analyst', 94836, 2009, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_390', 45, 'Marketing', 'Marketing Coordinator', 78952, 2017, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_391', 42, 'Operations', 'Logistics Manager', 91254, 2019, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_392', 54, 'Sales', 'Sales Associate', 57943, 2010, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_393', 25, 'Operations', 'Logistics Manager', 80150, 2024, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_394', 30, 'Marketing', 'Marketing Coordinator', 84837, 2013, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_395', 36, 'HR', 'HR Coordinator', 76734, 2001, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_396', 58, 'Operations', 'Supply Chain Analyst', 67393, 2009, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_397', 54, 'Sales', 'Account Executive', 61937, 2011, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_398', 42, 'HR', 'HR Manager', 95676, 2019, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_399', 27, 'Engineering', 'Software Engineer', 114677, 2009, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_400', 45, 'HR', 'HR Manager', 66109, 2019, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_401', 48, 'HR', 'HR Manager', 87105, 2011, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_402', 34, 'Operations', 'Supply Chain Analyst', 92997, 2023, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_403', 42, 'Sales', 'Sales Manager', 60852, 2018, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_404', 40, 'Operations', 'Logistics Manager', 98651, 2010, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_405', 47, 'Marketing', 'SEO Specialist', 83175, 2021, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_406', 27, 'Engineering', 'Data Engineer', 110926, 2006, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_407', 42, 'Finance', 'Financial Analyst', 74050, 2013, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_408', 55, 'Marketing', 'Marketing Coordinator', 76223, 2005, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_409', 48, 'HR', 'HR Manager', 93650, 2014, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_410', 25, 'Sales', 'Sales Manager', 101769, 2005, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_411', 35, 'Finance', 'Financial Analyst', 100908, 2020, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_412', 38, 'Finance', 'Accountant', 91941, 2019, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_413', 43, 'Sales', 'Account Executive', 66875, 2009, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_414', 52, 'Operations', 'Supply Chain Analyst', 77587, 2000, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_415', 24, 'HR', 'Talent Acquisition', 84748, 2019, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_416', 47, 'HR', 'HR Coordinator', 55652, 2022, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_417', 33, 'Finance', 'Financial Analyst', 79702, 2013, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_418', 53, 'Engineering', 'DevOps Engineer', 98025, 2022, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_419', 27, 'Sales', 'Account Executive', 68490, 2005, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_420', 58, 'Marketing', 'Brand Manager', 90448, 2011, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_421', 29, 'Finance', 'Financial Analyst', 104240, 2011, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_422', 57, 'Marketing', 'Marketing Coordinator', 62912, 2000, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_423', 25, 'Operations', 'Logistics Manager', 63587, 2004, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_424', 44, 'Finance', 'Accountant', 90943, 2008, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_425', 52, 'HR', 'Talent Acquisition', 53103, 2003, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_426', 38, 'HR', 'Talent Acquisition', 60140, 2002, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_427', 42, 'Marketing', 'Marketing Coordinator', 50542, 2008, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_428', 56, 'Sales', 'Sales Associate', 45705, 2015, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_429', 24, 'HR', 'HR Manager', 100963, 2024, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_430', 25, 'Engineering', 'ML Engineer', 82288, 2002, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_431', 51, 'HR', 'HR Manager', 83516, 2004, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_432', 29, 'HR', 'Talent Acquisition', 68255, 2008, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_433', 25, 'Sales', 'Account Executive', 69284, 2021, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_434', 32, 'Finance', 'Accountant', 94228, 2005, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_435', 56, 'Sales', 'Account Executive', 52811, 2015, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_436', 42, 'HR', 'Talent Acquisition', 58687, 2024, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_437', 36, 'HR', 'Talent Acquisition', 58440, 2013, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_438', 48, 'HR', 'HR Coordinator', 68126, 2001, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_439', 56, 'Engineering', 'ML Engineer', 107190, 2015, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_440', 39, 'Engineering', 'Software Engineer', 63991, 2016, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_441', 33, 'Engineering', 'DevOps Engineer', 95506, 2006, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_442', 30, 'Marketing', 'SEO Specialist', 78082, 2000, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_443', 56, 'Engineering', 'DevOps Engineer', 93458, 2003, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_444', 26, 'Sales', 'Sales Manager', 86283, 2004, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_445', 29, 'HR', 'Talent Acquisition', 69943, 2000, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_446', 40, 'Operations', 'Supply Chain Analyst', 74199, 2015, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_447', 48, 'Marketing', 'Brand Manager', 81844, 2006, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_448', 27, 'Finance', 'Finance Manager', 118076, 2001, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_449', 48, 'HR', 'HR Coordinator', 73300, 2019, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_450', 54, 'Marketing', 'Marketing Coordinator', 65595, 2003, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_451', 51, 'Operations', 'Operations Coordinator', 72525, 2002, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_452', 56, 'Engineering', 'Data Engineer', 123079, 2001, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_453', 54, 'Operations', 'Logistics Manager', 106170, 2017, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_454', 27, 'Operations', 'Logistics Manager', 87290, 2019, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_455', 42, 'Marketing', 'SEO Specialist', 52167, 2013, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_456', 26, 'HR', 'HR Manager', 80880, 2019, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_457', 52, 'HR', 'HR Manager', 108597, 2004, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_458', 27, 'Finance', 'Financial Analyst', 83338, 2012, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_459', 44, 'Engineering', 'DevOps Engineer', 102492, 2018, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_460', 55, 'Finance', 'Financial Analyst', 87915, 2008, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_461', 29, 'Engineering', 'Software Engineer', 63684, 2021, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_462', 41, 'HR', 'HR Coordinator', 79717, 2009, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_463', 51, 'Sales', 'Sales Manager', 70990, 2009, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_464', 36, 'Engineering', 'Software Engineer', 95160, 2010, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_465', 46, 'Engineering', 'ML Engineer', 91650, 2009, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_466', 48, 'Marketing', 'Brand Manager', 61585, 2005, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_467', 25, 'HR', 'HR Manager', 93560, 2001, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_468', 56, 'Marketing', 'Marketing Coordinator', 63345, 2001, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_469', 55, 'Operations', 'Logistics Manager', 69282, 2023, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_470', 32, 'Sales', 'Sales Associate', 68311, 2015, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_471', 33, 'Marketing', 'SEO Specialist', 74414, 2004, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_472', 29, 'Operations', 'Operations Coordinator', 70471, 2022, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_473', 44, 'Operations', 'Logistics Manager', 102302, 2018, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_474', 44, 'HR', 'HR Coordinator', 57584, 2018, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_475', 44, 'Marketing', 'Brand Manager', 94949, 2000, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_476', 33, 'Operations', 'Operations Coordinator', 77638, 2022, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_477', 27, 'Engineering', 'ML Engineer', 140386, 2019, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_478', 57, 'Finance', 'Finance Manager', 104884, 2000, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_479', 39, 'Marketing', 'SEO Specialist', 76085, 2011, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_480', 38, 'Sales', 'Account Executive', 56340, 2009, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_481', 45, 'HR', 'Talent Acquisition', 52283, 2010, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_482', 54, 'HR', 'HR Coordinator', 68000, 2002, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_483', 33, 'Finance', 'Finance Manager', 110927, 2024, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_484', 48, 'Marketing', 'Marketing Coordinator', 60234, 2005, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_485', 58, 'Marketing', 'Brand Manager', 99404, 2000, 'LATIN AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_486', 24, 'Finance', 'Finance Manager', 82552, 2005, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_487', 50, 'Marketing', 'Brand Manager', 98803, 2020, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_488', 44, 'Sales', 'Account Executive', 61155, 2001, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_489', 25, 'Marketing', 'Marketing Coordinator', 61585, 2016, 'NORTH AMERICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_490', 39, 'Operations', 'Supply Chain Analyst', 96527, 2012, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_491', 53, 'Engineering', 'Data Engineer', 115867, 2008, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_492', 24, 'Finance', 'Finance Manager', 87491, 2014, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_493', 57, 'Sales', 'Sales Associate', 43704, 2019, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_494', 32, 'HR', 'Talent Acquisition', 76256, 2002, 'ASIA-PACIFIC');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_495', 22, 'Sales', 'Sales Associate', 77117, 2009, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_496', 33, 'Sales', 'Sales Manager', 88963, 2006, 'MIDDLE EAST');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_497', 26, 'Engineering', 'Data Engineer', 102533, 2006, 'AFRICA');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_498', 33, 'Engineering', 'ML Engineer', 101463, 2015, 'EUROPE');
INSERT INTO employees (name, age, department, position, salary, year_joined, region) VALUES ('Employee_499', 32, 'Sales', 'Account Executive', 58678, 2018, 'AFRICA');
